# Generated by Django 5.1.8 on 2025-05-25 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('max_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'Aircraft',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('icao', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('gmt_offset', models.CharField(default='+12:00', max_length=6)),
            ],
            options={
                'db_table': 'Airport',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=6)),
                ('dep_dt', models.DateTimeField()),
                ('arr_dt', models.DateTimeField()),
                ('seats_avail', models.IntegerField()),
                ('base_price', models.FloatField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='app.aircraft')),
                ('arr_icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arr_icao', to='app.airport')),
                ('dep_icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_icao', to='app.airport')),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ref', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('tickets', models.IntegerField()),
                ('depart_price', models.FloatField()),
                ('return_price', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='app.customer')),
                ('depart_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_schedule', to='app.schedule')),
                ('return_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_schedule', to='app.schedule')),
            ],
            options={
                'db_table': 'Booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
